### ISSUE TITLE
Border and background-color for code blocks

### ISSUE THREAD

**Issue by Maskedman99** [markedjs/marked#1669]
**Describe the feature**
Apply border and background-color on Code Blocks
hello  =>  ```hello```

**Why is this feature necessary?**
This helps to separate text from code blocks

**Comment by styfle** [comment]
You can add [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) to change the style of code blocks.

```css
code {
  border: 1px solid gray;
  background-color: rgba(27,31,35,0.05);
}
```

For example: https://github.com/markedjs/marked/blob/92998df2ccea5c8587fbe73b6464a86972313fc0/docs/index.html#L106-L112
