### ISSUE TITLE
Confusing to properly integrate with HighlightJS.

### ISSUE THREAD

**Issue by theengineear** [markedjs/marked#2171]
## Overview

👋 — Hi there! In a nutshell, I'm having trouble getting `highlight.js` to work completely with `marked`. I can't figure out how to get the top-level `hljs` class added to the `code` tag without doing something like `langPrefix: 'hljs language-'` which _works_, but sorta feels like a hack!. Here's a [JSFiddle](https://jsfiddle.net/theengineear/9opab365/latest) to reproduce the issue I'm seeing!

<img width="1676" alt="Screen Shot 2021-08-13 at 4 12 23 PM" src="https://user-images.githubusercontent.com/6611546/129426376-f32fc647-462d-48a5-a308-cc6729df46ae.png">

## Some Additional Context

All of the CSS for `highlight.js` begins with a block that looks more-or-less like this:

```css
pre code.hljs {
  display: block;
  overflow-x: auto;
  padding: 1em;
}

code.hljs {
  padding: 3px 5px;
}

.hljs {
  background: #fefefe;
  color:#545454;
}

/* all the rest of the CSS works and isn't relevant to the conversation */
```

When you try to use `hljs.highlight` to highlight a block of code via `marked`, there doesn't seem to be a hook to add the `.hljs` class to the wrapping `code` element. I.e., you get `<code class="language-javascript">/* blah blah */<code>` when _what you want_ is `<code class="language-javascript hljs">/* blah blah */<code>`.
