### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by mazing** [markedjs/marked#545]
Is it possible to get a list of all headers in order to create a table of contents?

**Comment by paxidently** [comment]
Just define custom renderer. Like this:

````js
var renderer = new marked.Renderer();

var toc = [];

renderer.heading = function(text, level, raw) {
    var anchor = this.options.headerPrefix + raw.toLowerCase().replace(/[^\w]+/g, '-');
    toc.push({
        anchor: anchor,
        level: level,
        text: text
    });
    return '<h'
        + level
        + ' id="'
        + anchor
        + '">'
        + text
        + '</h'
        + level
        + '>\n';
};

marked.setOptions({
    renderer: renderer
});
````

**Comment by anaran** [comment]
Worked great for me, thanks!

```
  // See
  // https://github.com/chjj/marked/issues/545#issuecomment-74505539
  var toc = [];
  var renderer = (function() {
    var renderer = new marked.Renderer();
    renderer.heading = function(text, level, raw) {
      var anchor = this.options.headerPrefix + raw.toLowerCase().replace(/[^\w]+/g, '-');
      toc.push({
        anchor: anchor,
        level: level,
        text: text
      });
      return '<h'
      + level
      + ' id="'
      + anchor
      + '">'
      + text
      + '</h'
      + level
      + '>\n'
      + '<a href="#table-of-contents">Table of Contents<a>\n';
    };
    return renderer;
  })();

  marked.setOptions({
    renderer: renderer,
    gfm: true,
    tables: true,
    breaks: false,
    pedantic: false,
    sanitize: true,
    smartLists: true,
    smartypants: false
  });

          var html = marked(request.response);
          var tocHTML = '<h1 id="table-of-contents">Table of Contents</h1>\n<ul>';
          toc.forEach(function (entry) {
            tocHTML += '<li><a href="#'+entry.anchor+'">'+entry.text+'<a></li>\n';
          });
          tocHTML += '</ul>\n';
          document.querySelector('#render_markdown').innerHTML = tocHTML + html;
```

**Comment by joshbruce** [comment]
Closing as out of scope based on current focus.

See #956

**Comment by yzfdjzwl** [comment]
Those answers above, only support English, do not support English.So I add some rules based on the example above:

```javascript
var anchor = this.options.headerPrefix + raw.toLowerCase().replace(/[^\w\\u4e00-\\u9fa5]]+/g, '-');
```

Hope it can help we Chinese.

**Comment by joshbruce** [comment]
@UziTech and @Feder1co5oave: Check the pseudo PR from @yzfdjzwl. This intrigues me. I know I made the comment in #1043 about possibly deprecating the header `id` functionality, but this seems intriguing considering how many times I've seen this type of thing in some of the issues.

**Comment by joshbruce** [comment]
#1048

**Comment by ibreathebsb** [comment]
#1489

**Comment by watercoldyi** [comment]
Those answers above,do not support multi-level tree TOC. So I add some code based on the example above:
```javascript
 
var toc = [];
var renderer = (function () {
    var renderer = new marked.Renderer();
    renderer.heading = function (text, level, raw) {
        var anchor = this.options.headerPrefix + raw.toLowerCase().replace(/[^\w\\u4e00-\\u9fa5]]+/g, '-');
        toc.push({
            anchor: anchor,
            level: level,
            text: text
        });
        return '<h'
            + level
            + ' id="'
            + anchor
            + '">'
            + text
            + '</h'
            + level
            + '>\n'
            + '<a href="#table-of-contents">Table of Contents<a>\n';
    };
    return renderer;
})();

marked.setOptions({
    renderer: renderer,
    gfm: true,
    tables: true,
    breaks: false,
    pedantic: false,
    sanitize: true,
    smartLists: true,
    smartypants: false
});
function build(coll, k, level, ctx) {
    if (k >= coll.length || coll[k].level <= level) { return k; }
    var node = coll[k];
    ctx.push("<li><a href='#" + node.anchor + "'>" + node.text + "</a>");
    k++;
    var childCtx = [];
    k = build(coll, k, node.level, childCtx);
    if (childCtx.length > 0) {
        ctx.push("<ul>");
        childCtx.forEach(function (idm) {
            ctx.push(idm);
        });
        ctx.push("</ul>");
    }
    ctx.push("</li>");
    k = build(coll, k, level, ctx);
    return k;
}
var html = marked(data);
var ctx = [];
ctx.push('<h1 id="table-of-contents">Table of Contents</h1>\n<ul>');
build(toc, 0, 0, ctx);
ctx.push("</ul>");
document.querySelector('#content').innerHTML = ctx.join("") + html;
```

**Comment by jenstornell** [comment]
I've made a TOC solution where the javascript is less complicated but still supports nesting, at least visually.

![toc](https://user-images.githubusercontent.com/927011/65750160-04524800-e108-11e9-8926-c69080410c91.png)

**Javascript**

I did not need clickable headings, but if you need it, look at the first comment in this issue.

```js
const renderer = new marked.Renderer();
const r = {
  heading: renderer.heading.bind(renderer),
};

let toc = [];

renderer.heading = (text, level, raw, slugger) => {
  toc.push({
    level: level,
    text: text
  });

  return r.heading(text, level, raw, slugger);
};
```

I use Vue so I output the data in a template like this.

```html
<h3>Table of contents</h3>
<div class="list">
  <component class="h" v-for="h, index in toc" :is="'h' + h.level" :key="index" :title="'h' + h.level">
    {{ h.text }}
  </component>
</div>
```

**SCSS**

The nesting is made with pure CSS (SCSS). The different heading tags have different margins.

```scss
.list {
  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    font-size: 13px;
    font-weight: normal;
    display: flex;

    &:before {
      width: 20px;
      min-width: 20px;
      display: block;
      opacity: .5;
    }
  }

  h1 {
    &:before {
      content: '1\00a0 ';
    }
  }

  h2 {
    &:before {
      content: '2\00a0 ';
      margin-right: 1rem;
    }
  }

  h3 {
    &:before {
      content: '3\00a0 ';
      margin-right: 2rem;
    }
  }

  h4 {
    &:before {
      content: '4\00a0 ';
      margin-right: 3rem;
    }
  }

  h5 {
    &:before {
      content: '5\00a0 ';
      margin-right: 4rem;
    }
  }

  h6 {
    &:before {
      content: '6\00a0 ';
      margin-right: 5rem;
    }
  }
}
```
